apiVersion: v1
kind: Service
metadata:
   name: asset-transfer-basic
spec:
 selector:
   name: asset-transfer-basic.org1.example.com
 ports:
   - name: listen
     protocol: TCP
     port: 9999
     targetPort: 9999
---
apiVersion: v1
kind: Pod
metadata:
  name: asset-transfer-basic.org1.example.com
  labels:
     name: asset-transfer-basic.org1.example.com
spec:
      restartPolicy: Never
      volumes:
      - name: cacerts
        secret:
          secretName: hlf-ca-idcert
      - name: tls-cacerts
        secret:
          secretName: hlf-tlsca-idcert
      - name: admincerts
        secret:
          secretName: hlf-admin-idcert
      imagePullSecrets:
        - name: fabric-tools-secrets     
      containers:
      - name: asset-transfer-basic
        image: sitapseacr.azurecr.io/hlf/asset-transfer-basic:latest
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /var/hyperledger/msp/tlscacerts
          name: tls-cacerts
          readOnly: true
        - mountPath: /var/hyperledger/msp/admincerts
          name: admincerts
          readOnly: true        
        env:
        - name: GOPATH
          value: /var/hyperledger
        - name: CORE_PEER_ID
          value: cli
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /var/hyperledger/msp/tlscacerts/ca.crt
        - name: CORE_PEER_TLS_CLIENTAUTHREQUIRED
          value: "true"
        - name: CORE_PEER_TLS_CLIENTCERT_FILE
          value: /var/hyperledger/tls/cert.pem
        - name: CORE_PEER_TLS_CLIENTKEY_FILE
          value: /var/hyperledger/tls/key.pem
        - name: CORE_PEER_TLS_CLIENTROOTCAS_FILES
          value: /var/hyperledger/msp/tlscacerts/ca.crt
        - name: CORE_PEER_MSPCONFIGPATH
          value: /var/hyperledger/msp
        - name: FABRIC_CFG_PATH
          value: /usr/local/config/sampleconfig/
          value: /var/hyperledger/msp/admincerts/cert.pem
        - name: CLIENT_KEY
          value: /var/hyperledger/msp/keystore/key.pem
        - name: CA_FILE
          value: /var/hyperledger/msp/tlscacerts/ca.crt
        - name: CHAINCODE_ID
          value: "basic_1.0:097e077eccc1f16deefebf80575e09b18d4f08dba862e9c333cbe32ea2a02386"
        - name: CHAINCODE_SERVER_ADDRESS
          value: "asset-transfer-basic.org1.example.com:9999"   
